#! /bin/zsh

export ERL_LIBS=/home/cji/poligon/reqviewer
if rebar compile; then
    erl \
        -pa deps/cowboy/ebin deps/cowlib/ebin deps/goldrush/ebin \
            deps/lager/ebin deps/ranch/ebin deps/eredis/ebin/ \
            deps/jiffy/ebin/ \
        -pz ./ebin \
        -config app.config \
        -sname reqviewer \
        -s reqviewer_app
fi;
