#! /usr/bin/env bash

export ERL_LIBS=`pwd`           # NOTE: current dir HAS to be named reqviewer!
                                # otherwise Erlang won't find staticfiles

if [[ "$REDIS_HOST" ]]; then
    sed "s/\"127.0.0.1\"/\"$REDIS_HOST\"/" app.config.sample > app.config
fi

if [[ ! "$HOME" && -d /home/app ]]; then
    # chances are we're running inside a docker container, which is stupid and
    # doesn't set $HOME at all, so let's fix it
    export HOME="/home/app"
fi

if ./rebar compile; then
    erl \
        -pa deps/*/ebin \
        -pz ./ebin \
        -config app.config \
        -sname reqviewer \
        -s reqviewer_app
fi
